name: WirelessRedstone
version: '${project.version}'
main: xyz.pixelsky.wirelessredstone.WirelessRedstone
api-version: 1.16
authors: [ pixelsky ]
description: Plugin for Wireless Redstone.
website: https://pixelsky.xyz/

commands:
  device:
    usage: "/device <info/give/link>"
    description: "View, give or manage Redstone Devices."
  wirelessredstone:
    aliases: "wr"
    usage: "/wirelessredstone <info/reload/disable>"
    description: "Manage the WirelessRedstone plugin."